In [1]:
!pip install -r requirements.txt

Requirement already satisfied: corus in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (0.10.0)
Requirement already satisfied: pandas in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (2.3.2)
Requirement already satisfied: nltk in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (3.9.1)
Requirement already satisfied: scikit-learn in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (1.7.2)
Requirement already satisfied: gensim in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (4.3.3)
Requirement already satisfied: natasha in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 6)) (1.6.0)
Requirement already satisfied: matplotlib in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 7)) (3.10.6)
Requirement already satisfied: torch in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 8)) (2.8.0)
Requirement already satisfied: subword-nmt in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 9)) (0.3.8)
Requirement already satisfied: datasets in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 10)) (4.1.0)
Requirement already satisfied: evaluate in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 11)) (0.4.5)
Requirement already satisfied: seqeval in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 12)) (1.2.2)
Requirement already satisfied: transformers in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 13)) (4.56.1)
Requirement already satisfied: tabulate in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 14)) (0.9.0)
Requirement already satisfied: accelerate in ./nlp-env/lib/python3.12/site-packages (from -r requirements.txt (line 15)) (1.10.1)
Requirement already satisfied: numpy>=1.26.0 in ./nlp-env/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 2)) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./nlp-env/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./nlp-env/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./nlp-env/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: click in ./nlp-env/lib/python3.12/site-packages (from nltk->-r requirements.txt (line 3)) (8.2.1)
Requirement already satisfied: joblib in ./nlp-env/lib/python3.12/site-packages (from nltk->-r requirements.txt (line 3)) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in ./nlp-env/lib/python3.12/site-packages (from nltk->-r requirements.txt (line 3)) (2025.9.1)
Requirement already satisfied: tqdm in ./nlp-env/lib/python3.12/site-packages (from nltk->-r requirements.txt (line 3)) (4.67.1)
Requirement already satisfied: scipy>=1.8.0 in ./nlp-env/lib/python3.12/site-packages (from scikit-learn->-r requirements.txt (line 4)) (1.13.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./nlp-env/lib/python3.12/site-packages (from scikit-learn->-r requirements.txt (line 4)) (3.6.0)
Requirement already satisfied: smart-open>=1.8.1 in ./nlp-env/lib/python3.12/site-packages (from gensim->-r requirements.txt (line 5)) (7.3.1)
Requirement already satisfied: pymorphy2 in ./nlp-env/lib/python3.12/site-packages (from natasha->-r requirements.txt (line 6)) (0.9.1)
Requirement already satisfied: razdel>=0.5.0 in ./nlp-env/lib/python3.12/site-packages (from natasha->-r requirements.txt (line 6)) (0.5.0)
Requirement already satisfied: navec>=0.9.0 in ./nlp-env/lib/python3.12/site-packages (from natasha->-r requirements.txt (line 6)) (0.10.0)
Requirement already satisfied: slovnet>=0.6.0 in ./nlp-env/lib/python3.12/site-packages (from natasha->-r requirements.txt (line 6)) (0.6.0)
Requirement already satisfied: yargy>=0.16.0 in ./nlp-env/lib/python3.12/site-packages (from natasha->-r requirements.txt (line 6)) (0.16.0)
Requirement already satisfied: ipymarkup>=0.8.0 in ./nlp-env/lib/python3.12/site-packages (from natasha->-r requirements.txt (line 6)) (0.9.0)
Requirement already satisfied: contourpy>=1.0.1 in ./nlp-env/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 7)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./nlp-env/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 7)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./nlp-env/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 7)) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in ./nlp-env/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 7)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in ./nlp-env/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 7)) (25.0)
Requirement already satisfied: pillow>=8 in ./nlp-env/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 7)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in ./nlp-env/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 7)) (3.2.4)
Requirement already satisfied: filelock in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (4.15.0)
Requirement already satisfied: setuptools in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (1.14.0)
Requirement already satisfied: networkx in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (3.5)
Requirement already satisfied: jinja2 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (3.1.6)
Requirement already satisfied: fsspec in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (2025.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in ./nlp-env/lib/python3.12/site-packages (from torch->-r requirements.txt (line 8)) (3.4.0)
Requirement already satisfied: mock in ./nlp-env/lib/python3.12/site-packages (from subword-nmt->-r requirements.txt (line 9)) (5.2.0)
Requirement already satisfied: pyarrow>=21.0.0 in ./nlp-env/lib/python3.12/site-packages (from datasets->-r requirements.txt (line 10)) (21.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in ./nlp-env/lib/python3.12/site-packages (from datasets->-r requirements.txt (line 10)) (0.4.0)
Requirement already satisfied: requests>=2.32.2 in ./nlp-env/lib/python3.12/site-packages (from datasets->-r requirements.txt (line 10)) (2.32.5)
Requirement already satisfied: xxhash in ./nlp-env/lib/python3.12/site-packages (from datasets->-r requirements.txt (line 10)) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in ./nlp-env/lib/python3.12/site-packages (from datasets->-r requirements.txt (line 10)) (0.70.16)
Requirement already satisfied: huggingface-hub>=0.24.0 in ./nlp-env/lib/python3.12/site-packages (from datasets->-r requirements.txt (line 10)) (0.35.0)
Requirement already satisfied: pyyaml>=5.1 in ./nlp-env/lib/python3.12/site-packages (from datasets->-r requirements.txt (line 10)) (6.0.2)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./nlp-env/lib/python3.12/site-packages (from transformers->-r requirements.txt (line 13)) (0.22.0)
Requirement already satisfied: safetensors>=0.4.3 in ./nlp-env/lib/python3.12/site-packages (from transformers->-r requirements.txt (line 13)) (0.6.2)
Requirement already satisfied: psutil in ./nlp-env/lib/python3.12/site-packages (from accelerate->-r requirements.txt (line 15)) (7.0.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in ./nlp-env/lib/python3.12/site-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets->-r requirements.txt (line 10)) (3.12.15)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./nlp-env/lib/python3.12/site-packages (from huggingface-hub>=0.24.0->datasets->-r requirements.txt (line 10)) (1.1.10)
Requirement already satisfied: intervaltree>=3 in ./nlp-env/lib/python3.12/site-packages (from ipymarkup>=0.8.0->natasha->-r requirements.txt (line 6)) (3.1.0)
Requirement already satisfied: six>=1.5 in ./nlp-env/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 2)) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./nlp-env/lib/python3.12/site-packages (from requests>=2.32.2->datasets->-r requirements.txt (line 10)) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in ./nlp-env/lib/python3.12/site-packages (from requests>=2.32.2->datasets->-r requirements.txt (line 10)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./nlp-env/lib/python3.12/site-packages (from requests>=2.32.2->datasets->-r requirements.txt (line 10)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./nlp-env/lib/python3.12/site-packages (from requests>=2.32.2->datasets->-r requirements.txt (line 10)) (2025.8.3)
Requirement already satisfied: wrapt in ./nlp-env/lib/python3.12/site-packages (from smart-open>=1.8.1->gensim->-r requirements.txt (line 5)) (1.17.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./nlp-env/lib/python3.12/site-packages (from sympy>=1.13.3->torch->-r requirements.txt (line 8)) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./nlp-env/lib/python3.12/site-packages (from jinja2->torch->-r requirements.txt (line 8)) (3.0.2)
Requirement already satisfied: dawg-python>=0.7.1 in ./nlp-env/lib/python3.12/site-packages (from pymorphy2->natasha->-r requirements.txt (line 6)) (0.7.2)
Requirement already satisfied: pymorphy2-dicts-ru<3.0,>=2.4 in ./nlp-env/lib/python3.12/site-packages (from pymorphy2->natasha->-r requirements.txt (line 6)) (2.4.417127.4579844)
Requirement already satisfied: docopt>=0.6 in ./nlp-env/lib/python3.12/site-packages (from pymorphy2->natasha->-r requirements.txt (line 6)) (0.6.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in ./nlp-env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets->-r requirements.txt (line 10)) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in ./nlp-env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets->-r requirements.txt (line 10)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in ./nlp-env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets->-r requirements.txt (line 10)) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./nlp-env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets->-r requirements.txt (line 10)) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./nlp-env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets->-r requirements.txt (line 10)) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in ./nlp-env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets->-r requirements.txt (line 10)) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./nlp-env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets->-r requirements.txt (line 10)) (1.20.1)
Requirement already satisfied: sortedcontainers<3.0,>=2.0 in ./nlp-env/lib/python3.12/site-packages (from intervaltree>=3->ipymarkup>=0.8.0->natasha->-r requirements.txt (line 6)) (2.4.0)

In [2]:
# pip install --upgrade transformers accelerate

In [3]:
import pathlib as pl
import requests
import zipfile
from corus import load_ne5, load_lenta
import re
from datasets import Dataset, Sequence, ClassLabel
from transformers import (
    AutoTokenizer, AutoModelForTokenClassification,
    AutoModelForMaskedLM,
    TrainingArguments, Trainer,
    DataCollatorForTokenClassification,
    DataCollatorForLanguageModeling
)
import evaluate
import numpy as np
import tabulate
import torch

/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"

print(device)

cpu

In [5]:
url = "http://www.labinform.ru/pub/named_entities/collection5.zip"

path = "Collection5.zip"
zip_path = pl.Path.cwd()/path

if not pl.Path.exists(zip_path):
    response = requests.get(url, stream=True)
    if response.status_code == 200:
        with open(path, "wb") as file:
            for chunk in response.iter_content(chunk_size=8192):
                file.write(chunk)
        print("Файл успешно загружен.")
    else:
        print("Ошибка при загрузке файла")
else:
    print("Файл уже существует")

Файл уже существует

In [6]:
extract_dir = pl.Path.cwd()
if pl.Path.exists(zip_path):
    with zipfile.ZipFile(path, 'r') as zip_ref:
        zip_ref.extractall(extract_dir)

    if not pl.Path.exists(extract_dir):
        pl.Path.mkdir(extract_dir, exist_ok=True)

    print("Архив распакован")
else:
    print("Файл не существует.")

Архив распакован

In [7]:
dataset = load_ne5("Collection5")

In [8]:
next(dataset)

Ne5Markup(
    id='479',
    text='С.Собянин назначил глав управ районов трех округов Москвы.\r\n\r\nМэр Москвы Сергей Собянин назначил глав управ районов трех округов Москвы. Как сообщили РБК в правительстве столицы, соответствующие распоряжения уже подписаны. Назначены главы управ в Северном, Западном и Южном административных округах города.\r\n\r\nВ Северном округе назначены главы управ 8 районов. Управу района Сокол возглавил Виталий Аксенов, Дмитровского района - Владимир Назаров, Западного Дегунино - Сергей Овчинников, Савеловского - Станислав Одиноков, Тимирязевского - Владимир Палкин, Коптево - Владимир Перов, Войковского - Сергей Сидоров, Левобережного - Виктор Ярцев.\r\n\r\nВ Западном округе назначены 13 глав управ районов. Район Внуково возглавил Павел Авеков, Солнцево - Константин Бусыгин, Филевский парк - Антон Гудзь, Кунцево - Назим Намазов, Крылатское - Виталий Никитин, Очаково-Матвеевское - Сергей Новиков, Раменки - Игорь Окунев, Можайский - Михаил Решетников, Проспект Вернадского - Василий Урванов, Дорогомилово - Дмитрий Шалаев, Фили-Давыдково - Алексей Шестопалов, Тропарево-Никулино - Владимир Кушнир, Ново-Переделкино - Евгений Сорока.\r\n\r\nВ Южном округе назначены 9 глав управ. Даниловский район возглавил Олег Ворона, Орехово-Борисово Северное - Евгений Громов, Нагатинский затон - Ирина Джиоева, Орехово-Борисово Южное - Валентина Козельская, Чертаново Северное - Павел Кораблев, Бирюлево Западное - Виктор Легавин, Чертаново Центральное - Владимир Михеев, Братеево - Александра Синючкова, Царицыно - Вадим Чернышов.',
    spans=[Ne5Span(
         index='T1',
         type='PER',
         start=0,
         stop=9,
         text='С.Собянин'
     ),
     Ne5Span(
         index='T2',
         type='LOC',
         start=51,
         stop=57,
         text='Москвы'
     ),
     Ne5Span(
         index='T3',
         type='LOC',
         start=66,
         stop=72,
         text='Москвы'
     ),
     Ne5Span(
         index='T4',
         type='PER',
         start=73,
         stop=87,
         text='Сергей Собянин'
     ),
     Ne5Span(
         index='T5',
         type='LOC',
         start=129,
         stop=135,
         text='Москвы'
     ),
     Ne5Span(
         index='T6',
         type='MEDIA',
         start=150,
         stop=153,
         text='РБК'
     ),
     Ne5Span(
         index='T7',
         type='LOC',
         start=247,
         stop=255,
         text='Северном'
     ),
     Ne5Span(
         index='T8',
         type='LOC',
         start=257,
         stop=265,
         text='Западном'
     ),
     Ne5Span(
         index='T9',
         type='LOC',
         start=268,
         stop=298,
         text='Южном административных округах'
     ),
     Ne5Span(
         index='T10',
         type='LOC',
         start=312,
         stop=327,
         text='Северном округе'
     ),
     Ne5Span(
         index='T11',
         type='LOC',
         start=375,
         stop=380,
         text='Сокол'
     ),
     Ne5Span(
         index='T12',
         type='PER',
         start=391,
         stop=406,
         text='Виталий Аксенов'
     ),
     Ne5Span(
         index='T13',
         type='LOC',
         start=408,
         stop=427,
         text='Дмитровского района'
     ),
     Ne5Span(
         index='T14',
         type='PER',
         start=430,
         stop=446,
         text='Владимир Назаров'
     ),
     Ne5Span(
         index='T15',
         type='LOC',
         start=448,
         stop=466,
         text='Западного Дегунино'
     ),
     Ne5Span(
         index='T16',
         type='PER',
         start=469,
         stop=486,
         text='Сергей Овчинников'
     ),
     Ne5Span(
         index='T17',
         type='LOC',
         start=488,
         stop=500,
         text='Савеловского'
     ),
     Ne5Span(
         index='T18',
         type='PER',
         start=503,
         stop=521,
         text='Станислав Одиноков'
     ),
     Ne5Span(
         index='T19',
         type='LOC',
         start=523,
         stop=537,
         text='Тимирязевского'
     ),
     Ne5Span(
         index='T20',
         type='PER',
         start=540,
         stop=555,
         text='Владимир Палкин'
     ),
     Ne5Span(
         index='T21',
         type='LOC',
         start=557,
         stop=564,
         text='Коптево'
     ),
     Ne5Span(
         index='T22',
         type='PER',
         start=567,
         stop=581,
         text='Владимир Перов'
     ),
     Ne5Span(
         index='T23',
         type='LOC',
         start=583,
         stop=594,
         text='Войковского'
     ),
     Ne5Span(
         index='T24',
         type='PER',
         start=597,
         stop=611,
         text='Сергей Сидоров'
     ),
     Ne5Span(
         index='T25',
         type='LOC',
         start=613,
         stop=626,
         text='Левобережного'
     ),
     Ne5Span(
         index='T26',
         type='PER',
         start=629,
         stop=641,
         text='Виктор Ярцев'
     ),
     Ne5Span(
         index='T27',
         type='LOC',
         start=648,
         stop=663,
         text='Западном округе'
     ),
     Ne5Span(
         index='T28',
         type='LOC',
         start=703,
         stop=710,
         text='Внуково'
     ),
     Ne5Span(
         index='T29',
         type='PER',
         start=721,
         stop=733,
         text='Павел Авеков'
     ),
     Ne5Span(
         index='T30',
         type='LOC',
         start=735,
         stop=743,
         text='Солнцево'
     ),
     Ne5Span(
         index='T31',
         type='PER',
         start=746,
         stop=764,
         text='Константин Бусыгин'
     ),
     Ne5Span(
         index='T32',
         type='LOC',
         start=766,
         stop=780,
         text='Филевский парк'
     ),
     Ne5Span(
         index='T33',
         type='PER',
         start=783,
         stop=794,
         text='Антон Гудзь'
     ),
     Ne5Span(
         index='T34',
         type='LOC',
         start=796,
         stop=803,
         text='Кунцево'
     ),
     Ne5Span(
         index='T35',
         type='PER',
         start=806,
         stop=819,
         text='Назим Намазов'
     ),
     Ne5Span(
         index='T36',
         type='LOC',
         start=821,
         stop=831,
         text='Крылатское'
     ),
     Ne5Span(
         index='T37',
         type='PER',
         start=834,
         stop=849,
         text='Виталий Никитин'
     ),
     Ne5Span(
         index='T38',
         type='LOC',
         start=851,
         stop=870,
         text='Очаково-Матвеевское'
     ),
     Ne5Span(
         index='T39',
         type='PER',
         start=873,
         stop=887,
         text='Сергей Новиков'
     ),
     Ne5Span(
         index='T40',
         type='LOC',
         start=889,
         stop=896,
         text='Раменки'
     ),
     Ne5Span(
         index='T41',
         type='PER',
         start=899,
         stop=911,
         text='Игорь Окунев'
     ),
     Ne5Span(
         index='T42',
         type='LOC',
         start=913,
         stop=922,
         text='Можайский'
     ),
     Ne5Span(
         index='T43',
         type='PER',
         start=925,
         stop=942,
         text='Михаил Решетников'
     ),
     Ne5Span(
         index='T44',
         type='LOC',
         start=944,
         stop=964,
         text='Проспект Вернадского'
     ),
     Ne5Span(
         index='T45',
         type='PER',
         start=967,
         stop=982,
         text='Василий Урванов'
     ),
     Ne5Span(
         index='T46',
         type='LOC',
         start=984,
         stop=996,
         text='Дорогомилово'
     ),
     Ne5Span(
         index='T47',
         type='PER',
         start=999,
         stop=1013,
         text='Дмитрий Шалаев'
     ),
     Ne5Span(
         index='T48',
         type='LOC',
         start=1015,
         stop=1029,
         text='Фили-Давыдково'
     ),
     Ne5Span(
         index='T49',
         type='PER',
         start=1032,
         stop=1050,
         text='Алексей Шестопалов'
     ),
     Ne5Span(
         index='T50',
         type='LOC',
         start=1052,
         stop=1070,
         text='Тропарево-Никулино'
     ),
     Ne5Span(
         index='T51',
         type='PER',
         start=1073,
         stop=1088,
         text='Владимир Кушнир'
     ),
     Ne5Span(
         index='T52',
         type='LOC',
         start=1090,
         stop=1106,
         text='Ново-Переделкино'
     ),
     Ne5Span(
         index='T53',
         type='PER',
         start=1109,
         stop=1123,
         text='Евгений Сорока'
     ),
     Ne5Span(
         index='T54',
         type='LOC',
         start=1130,
         stop=1142,
         text='Южном округе'
     ),
     Ne5Span(
         index='T55',
         type='LOC',
         start=1167,
         stop=1184,
         text='Даниловский район'
     ),
     Ne5Span(
         index='T56',
         type='PER',
         start=1195,
         stop=1206,
         text='Олег Ворона'
     ),
     Ne5Span(
         index='T57',
         type='LOC',
         start=1208,
         stop=1233,
         text='Орехово-Борисово Северное'
     ),
     Ne5Span(
         index='T58',
         type='PER',
         start=1236,
         stop=1250,
         text='Евгений Громов'
     ),
     Ne5Span(
         index='T59',
         type='LOC',
         start=1252,
         stop=1269,
         text='Нагатинский затон'
     ),
     Ne5Span(
         index='T60',
         type='PER',
         start=1272,
         stop=1285,
         text='Ирина Джиоева'
     ),
     Ne5Span(
         index='T61',
         type='LOC',
         start=1287,
         stop=1309,
         text='Орехово-Борисово Южное'
     ),
     Ne5Span(
         index='T62',
         type='PER',
         start=1312,
         stop=1332,
         text='Валентина Козельская'
     ),
     Ne5Span(
         index='T63',
         type='LOC',
         start=1334,
         stop=1352,
         text='Чертаново Северное'
     ),
     Ne5Span(
         index='T64',
         type='PER',
         start=1355,
         stop=1369,
         text='Павел Кораблев'
     ),
     Ne5Span(
         index='T65',
         type='LOC',
         start=1371,
         stop=1388,
         text='Бирюлево Западное'
     ),
     Ne5Span(
         index='T66',
         type='PER',
         start=1391,
         stop=1405,
         text='Виктор Легавин'
     ),
     Ne5Span(
         index='T67',
         type='LOC',
         start=1407,
         stop=1428,
         text='Чертаново Центральное'
     ),
     Ne5Span(
         index='T68',
         type='PER',
         start=1431,
         stop=1446,
         text='Владимир Михеев'
     ),
     Ne5Span(
         index='T69',
         type='LOC',
         start=1448,
         stop=1456,
         text='Братеево'
     ),
     Ne5Span(
         index='T70',
         type='PER',
         start=1459,
         stop=1479,
         text='Александра Синючкова'
     ),
     Ne5Span(
         index='T71',
         type='LOC',
         start=1481,
         stop=1489,
         text='Царицыно'
     ),
     Ne5Span(
         index='T72',
         type='PER',
         start=1492,
         stop=1506,
         text='Вадим Чернышов'
     )]
)

In [9]:
def convert_markup_to_ner(item):
    text = item.text
    tokens = []
    offsets = []
    for match in re.finditer(r"\S+", text):
        tokens.append(match.group())
        offsets.append((match.start(), match.end()))

    labels = ["O"] * len(tokens)

    for span in item.spans:
        token_indices = [
            i for i, (tstart, tend) in enumerate(offsets) if not (tend <= span.start or tstart >= span.stop)
        ]
        if token_indices:
            labels[token_indices[0]] = "B-" + span.type
            for idx in token_indices[1:]:
                labels[idx] = "I-" + span.type

    return {"id": item.id, "tokens": tokens, "ner_tags": labels}

In [10]:
data_list = [convert_markup_to_ner(item) for item in dataset]
ner_dataset = Dataset.from_list(data_list)

In [11]:
unique_labels = set()
for example in ner_dataset:
    unique_labels.update(example["ner_tags"])

unique_labels = sorted(list(unique_labels))
label_to_id = {label: i for i, label in enumerate(unique_labels)}

In [12]:
label_to_id

{'B-GEOPOLIT': 0,
 'B-LOC': 1,
 'B-MEDIA': 2,
 'B-ORG': 3,
 'B-PER': 4,
 'I-GEOPOLIT': 5,
 'I-LOC': 6,
 'I-MEDIA': 7,
 'I-ORG': 8,
 'I-PER': 9,
 'O': 10}

In [13]:
def convert_labels(example):
    example["ner_tags"] = [label_to_id[label] for label in example["ner_tags"]]
    return example

In [14]:
ner_dataset = ner_dataset.map(convert_labels)

Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 999/999 [00:00<00:00, 6571.26 examples/s]

In [15]:
features = ner_dataset.features.copy()
features["ner_tags"] = Sequence(ClassLabel(names=unique_labels))
ner_dataset = ner_dataset.cast(features)

Casting the dataset: 100%|██████████████████████████████████████████████████████████████████████████████████| 999/999 [00:00<00:00, 193789.18 examples/s]

In [16]:
print(ner_dataset[0])

{'id': '15_01_13b', 'tokens': ['А.Хинштейн:', 'Руководство', '"Военторга"', 'попалось', 'на', 'продовольственной', 'афере', 'А.Хинштейн:', 'Руководство', '"Военторга"', 'попалось', 'на', 'продовольственной', 'афере', 'Руководство', 'ОАО', '"Военторг"', 'подозревается', 'в', 'злоупотреблении', 'полномочиями', 'при', 'поставках', 'продовольствия', 'в', 'армию.', 'Об', 'этом', 'сообщил', 'РБК', 'депутат', 'Государственной', 'думы', 'Александр', 'Хинштейн,', 'ссылаясь', 'на', 'ответ,', 'полученный', 'из', 'Главной', 'военной', 'прокуратуры', '(ГВП).', 'По', 'словам', 'депутата,', 'основные', 'претензии', 'у', 'правоохранительных', 'органов', 'к', 'теперь', 'уже', 'бывшей', 'главе', '"Военторга"', 'Марине', 'Лопатиной,', 'которая', 'лишилась', 'своего', 'поста', 'в', 'связи', 'с', 'расследованием', 'этого', 'дела.', 'Депутат', 'уточнил,', 'что', 'гендиректор', 'М.Лопатина', 'снята', 'с', 'должности', 'по', 'прокурорскому', 'представлению.', 'При', 'этом', 'А.Хинштейн', 'отметил,', 'что', 'конкретных', 'фигурантов', 'в', 'деле', 'пока', 'нет.', 'По', 'словам', 'депутата,', 'следствие', 'установило,', 'что', '"Военторг",', 'являясь', 'единственным', 'поставщиком', 'продовольствия', 'в', 'соответствии', 'с', 'контрактом', 'между', 'ним', 'и', 'Министерством', 'обороны', 'РФ,', 'в', 'свою', 'очередь', 'заключал', 'договоры', 'с', 'другими', 'поставщиками,', 'которые', 'включали', 'в', 'эту', 'цепочку', 'новых', 'посредников.', 'По', 'мнению', 'следствия,', 'это', 'повлекло', 'неоправданно', 'высокие', 'расходы', 'на', 'обеспечение', 'нужд', 'Вооруженных', 'сил', 'РФ', 'в', 'питании.', 'Уголовное', 'дело', 'по', 'данному', 'факту', 'было', 'возбуждено', '19', 'декабря', '2012г.', 'Напомним,', 'в', 'ноябре', '2012г.', 'А.Хинштейн', 'обратился', 'к', 'новому', 'министру', 'обороны', 'РФ,', 'генералу', 'армии', 'Сергею', 'Шойгу', 'с', 'просьбой', 'экстренно', 'вмешаться', 'в', 'ситуацию', 'вокруг', 'ОАО', '"Военторг".', 'Депутат', 'указывал', 'на', 'непрозрачность', 'работы', 'руководства', 'ОАО', '"Военторг"', 'с', 'контрагентами', 'компании.', '"Ждем', 'новых', 'уголовных', 'дел', 'и', 'увольнения', 'М.Лопатиной",', '-', 'заявил', 'тогда', 'депутат.'], 'ner_tags': [4, 10, 3, 10, 10, 10, 10, 4, 10, 3, 10, 10, 10, 10, 10, 3, 8, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 2, 10, 3, 8, 4, 9, 10, 10, 10, 10, 10, 3, 8, 8, 8, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 3, 4, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 4, 10, 10, 10, 10, 10, 10, 10, 10, 4, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 3, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 3, 8, 0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 3, 8, 0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 4, 10, 10, 10, 10, 10, 0, 10, 10, 4, 9, 10, 10, 10, 10, 10, 10, 10, 3, 8, 10, 10, 10, 10, 10, 10, 3, 8, 10, 10, 10, 10, 10, 10, 10, 10, 10, 4, 10, 10, 10, 10]}

In [17]:
tokenizer = AutoTokenizer.from_pretrained("cointegrated/rubert-tiny2")

In [18]:
def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True,
        max_length=128,
        padding="max_length"
    )
    all_labels = []
    for i, labels in enumerate(examples["ner_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []
        for word_idx in word_ids:
            if word_idx is None:
                label_ids.append(-100)
            elif word_idx != previous_word_idx:
                label_ids.append(labels[word_idx])
            else:
                label_ids.append(-100)
            previous_word_idx = word_idx
        all_labels.append(label_ids)
    tokenized_inputs["labels"] = all_labels
    return tokenized_inputs

In [19]:
tokenized_dataset = ner_dataset.map(tokenize_and_align_labels, batched=True)

Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 999/999 [00:00<00:00, 2433.63 examples/s]

In [20]:
tokenized_dataset = tokenized_dataset.train_test_split(test_size=0.2)

In [21]:
train_dataset = tokenized_dataset["train"]
test_dataset = tokenized_dataset["test"]

In [22]:
num_labels = len(unique_labels)
model = AutoModelForTokenClassification.from_pretrained("cointegrated/rubert-tiny2", num_labels=num_labels)

Some weights of BertForTokenClassification were not initialized from the model checkpoint at cointegrated/rubert-tiny2 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [23]:
training_args = TrainingArguments(
    output_dir="models/ner_results",
    eval_strategy="steps",
    save_strategy="steps",
    save_steps=1000,
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    max_steps=10000,
    logging_steps=500,
    weight_decay=0.01,
    logging_dir="./logs",
    report_to="none",
    load_best_model_at_end=True,
    save_total_limit=2,
)

In [24]:
metric = evaluate.load("seqeval")

In [25]:
label_list = tokenized_dataset['train'].features['ner_tags'].feature.names
print("Label list:", label_list)

Label list: ['B-GEOPOLIT', 'B-LOC', 'B-MEDIA', 'B-ORG', 'B-PER', 'I-GEOPOLIT', 'I-LOC', 'I-MEDIA', 'I-ORG', 'I-PER', 'O']

In [26]:
def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    true_predictions = [
        [label_list[p] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]
    true_labels = [
        [label_list[l] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]

    results = metric.compute(predictions=true_predictions, references=true_labels)
    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }

In [27]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=DataCollatorForTokenClassification(tokenizer=tokenizer),
    compute_metrics=compute_metrics
)

In [28]:
print("Метрики ДО дообучения:")
pre_training_results = trainer.evaluate()
print(tabulate.tabulate(
    pre_training_results.items(),
    headers=["Метрика", "Значение"],
    tablefmt="grid",
    floatfmt=".4f"
))

Метрики ДО дообучения:

/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

+-----------------------------+------------+
| Метрика                     |   Значение |
+=============================+============+
| eval_loss                   |     2.4678 |
+-----------------------------+------------+
| eval_model_preparation_time |     0.0018 |
+-----------------------------+------------+
| eval_precision              |     0.0151 |
+-----------------------------+------------+
| eval_recall                 |     0.0817 |
+-----------------------------+------------+
| eval_f1                     |     0.0255 |
+-----------------------------+------------+
| eval_accuracy               |     0.0549 |
+-----------------------------+------------+
| eval_runtime                |     0.7940 |
+-----------------------------+------------+
| eval_samples_per_second     |   251.8780 |
+-----------------------------+------------+
| eval_steps_per_second       |    16.3720 |
+-----------------------------+------------+

In [29]:
trainer.train()

/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

TrainOutput(global_step=10000, training_loss=0.029518825206160546, metrics={'train_runtime': 2734.5931, 'train_samples_per_second': 58.51, 'train_steps_per_second': 3.657, 'total_flos': 282960319641600.0, 'train_loss': 0.029518825206160546, 'epoch': 200.0})

In [30]:
print("Метрики ПОСЛЕ дообучения:")
post_training_results = trainer.evaluate()
print(tabulate.tabulate(
    post_training_results.items(),
    headers=["Метрика", "Значение"],
    tablefmt="grid",
    floatfmt=".4f"
))

Метрики ПОСЛЕ дообучения:

/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

+-----------------------------+------------+
| Метрика                     |   Значение |
+=============================+============+
| eval_loss                   |     0.1083 |
+-----------------------------+------------+
| eval_model_preparation_time |     0.0018 |
+-----------------------------+------------+
| eval_precision              |     0.8543 |
+-----------------------------+------------+
| eval_recall                 |     0.9031 |
+-----------------------------+------------+
| eval_f1                     |     0.8780 |
+-----------------------------+------------+
| eval_accuracy               |     0.9711 |
+-----------------------------+------------+
| eval_runtime                |     0.5624 |
+-----------------------------+------------+
| eval_samples_per_second     |   355.6420 |
+-----------------------------+------------+
| eval_steps_per_second       |    23.1170 |
+-----------------------------+------------+
| epoch                       |   200.0000 |
+-----------------------------+------------+

# Попробуйте улучшить качество модели

### Дообучение в MLM режиме на train части, а затем дообучение на NER

In [40]:
train_mlm_dataset = tokenized_dataset['train'].map(
    lambda example: {'text': ' '.join(example['tokens'])},
    remove_columns=tokenized_dataset['train'].column_names  # Удаляем все оригинальные колонки
)

Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 799/799 [00:00<00:00, 5101.08 examples/s]

In [41]:
train_mlm_dataset

Dataset({
    features: ['text'],
    num_rows: 799
})

In [42]:
mask_tokenizer = AutoTokenizer.from_pretrained("cointegrated/rubert-tiny2")

def tokenize_mlm(examples):
    result = mask_tokenizer(
        examples['text'],
        truncation=True,
        padding='max_length',
        max_length=256,
        return_special_tokens_mask=True
    )
    return result

tokenized_mlm_dataset = train_mlm_dataset.map(
    tokenize_mlm,
    batched=True,
    remove_columns=['text']
)

Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 799/799 [00:00<00:00, 5563.08 examples/s]

In [43]:
data_collator = DataCollatorForLanguageModeling(
    tokenizer=mask_tokenizer,
    mlm=True,
    mlm_probability=0.15
)

In [51]:
mlm_model = AutoModelForMaskedLM.from_pretrained("cointegrated/rubert-tiny2")

training_mlm_args = TrainingArguments(
    output_dir="models/mlm_results",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    learning_rate=5e-5,
    weight_decay=0.01,
    logging_steps=500,
    save_steps=1000,
    save_total_limit=2,
    prediction_loss_only=True,
    remove_unused_columns=False,
    logging_dir="./logs_mlm",
    report_to="none",
)

mlm_trainer = Trainer(
    model=mlm_model,
    args=training_mlm_args,
    train_dataset=tokenized_mlm_dataset,
    eval_dataset=test_dataset,
    data_collator=data_collator,
)

In [45]:
mlm_trainer.train()

TrainOutput(global_step=150, training_loss=3.145899658203125, metrics={'train_runtime': 556.829, 'train_samples_per_second': 4.305, 'train_steps_per_second': 0.269, 'total_flos': 9146616956928.0, 'train_loss': 3.145899658203125, 'epoch': 3.0})

In [55]:
mlm_trainer.save_model("models/mlm_finetuned_model")

In [56]:
mlm_nle_model = AutoModelForTokenClassification.from_pretrained(
    "models/mlm_finetuned_model", num_labels=num_labels,  # количество ваших NER классов
    # ignore_mismatched_sizes=True  # важно! меняем голову модели
)

Some weights of BertForTokenClassification were not initialized from the model checkpoint at models/mlm_finetuned_model and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [57]:
training_args = TrainingArguments(
    output_dir="models/mlm_ner_results",
    eval_strategy="steps",
    save_strategy="steps",
    save_steps=1000,
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    max_steps=10000,
    logging_steps=500,
    weight_decay=0.01,
    logging_dir="./logs",
    report_to="none",
    load_best_model_at_end=True,
    save_total_limit=2,
)

In [60]:
mlm_nle_trainer = Trainer(
    model=mlm_nle_model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=DataCollatorForTokenClassification(tokenizer=tokenizer),
    compute_metrics=compute_metrics
)

In [61]:
print("Метрики после дообучения в MLM режиме:")
mlm_training_results = mlm_nle_trainer.evaluate()
print(tabulate.tabulate(
    mlm_training_results.items(),
    headers=["Метрика", "Значение"],
    tablefmt="grid",
    floatfmt=".4f"
))

Метрики после дообучения в MLM режиме:

+-----------------------------+------------+
| Метрика                     |   Значение |
+=============================+============+
| eval_loss                   |     2.4774 |
+-----------------------------+------------+
| eval_model_preparation_time |     0.0012 |
+-----------------------------+------------+
| eval_precision              |     0.0184 |
+-----------------------------+------------+
| eval_recall                 |     0.1059 |
+-----------------------------+------------+
| eval_f1                     |     0.0313 |
+-----------------------------+------------+
| eval_accuracy               |     0.0610 |
+-----------------------------+------------+
| eval_runtime                |     0.6928 |
+-----------------------------+------------+
| eval_samples_per_second     |   288.6670 |
+-----------------------------+------------+
| eval_steps_per_second       |    18.7630 |
+-----------------------------+------------+

In [62]:
mlm_nle_trainer.train()

/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

TrainOutput(global_step=10000, training_loss=0.029506268256902696, metrics={'train_runtime': 2428.9375, 'train_samples_per_second': 65.872, 'train_steps_per_second': 4.117, 'total_flos': 282960319641600.0, 'train_loss': 0.029506268256902696, 'epoch': 200.0})

In [63]:
print("Метрики после дообучения на NER модели, дообученной на MLM режиме:")
mlm_training_results = mlm_nle_trainer.evaluate()
print(tabulate.tabulate(
    mlm_training_results.items(),
    headers=["Метрика", "Значение"],
    tablefmt="grid",
    floatfmt=".4f"
))

Метрики после дообучения на NER модели, дообученной на MLM режиме:

/home/semyon/python_projects/NLP/nlp-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

+-----------------------------+------------+
| Метрика                     |   Значение |
+=============================+============+
| eval_loss                   |     0.1122 |
+-----------------------------+------------+
| eval_model_preparation_time |     0.0012 |
+-----------------------------+------------+
| eval_precision              |     0.8542 |
+-----------------------------+------------+
| eval_recall                 |     0.9000 |
+-----------------------------+------------+
| eval_f1                     |     0.8765 |
+-----------------------------+------------+
| eval_accuracy               |     0.9706 |
+-----------------------------+------------+
| eval_runtime                |     0.6746 |
+-----------------------------+------------+
| eval_samples_per_second     |   296.4670 |
+-----------------------------+------------+
| eval_steps_per_second       |    19.2700 |
+-----------------------------+------------+
| epoch                       |   200.0000 |
+-----------------------------+------------+

### С синтетическими данными

In [ ]:
if not os.path.exists('lenta-ru-news.csv.gz'):
    !wget https://github.com/yutkin/Lenta.Ru-News-Dataset/releases/download/v1.0/lenta-ru-news.csv.gz